# Global Configuration
global:
  repoURL: https://github.com/kfiros94/geodish-gitops.git
  targetRevision: main
  namespace: argocd
  clusterName: geodish-eks-cluster

# Project Configuration
project:
  name: geodish-project
  description: GeoDish DevOps Bootcamp Project - Full Stack Application with GitOps

# Applications Configuration
applications:
  # MongoDB Database (Deploy First)
  mongodb-complete:
    name: mongodb-complete
    path: charts/mongodb-complete
    namespace: geodish-app
    syncWave: "1"
    enabled: true
    
  # GeoDish Flask Application (Deploy After Database)
  geodish-app:
    name: geodish-app
    path: charts/geodish-app  
    namespace: geodish-app
    syncWave: "2"
    enabled: true
    image:
      tag: "29"  # Updated by Jenkins Pipeline
      
  # Future: Monitoring Stack (Deploy Last)  
  monitoring:
    name: monitoring
    path: charts/monitoring
    namespace: monitoring
    syncWave: "3"
    enabled: false  # Enable when monitoring is ready

# Sync Policy Configuration
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    allowEmpty: false
  syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m

# Health Check Configuration  
health:
  timeout: 300
  checkInterval: 30
