apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geodish-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "geodish-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "geodish-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "geodish-app.selectorLabels" . | nindent 8 }}
    spec:
      # ADD THIS: Init container to seed database
      initContainers:
        - name: database-seeder
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "python -c 'from app.seed_manager import SeedManager; from app.models import Database; SeedManager(Database()).seed_database()' || true"]
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.secretName }}
                  key: {{ .Values.mongodb.connectionStringKey }}
      containers:
        - name: {{ .Chart.Name }}
          # ... rest of your existing container config
