# Application configuration
app:
  name: geodish-app
  image:
    repository: 893692751288.dkr.ecr.ap-south-1.amazonaws.com/geodish-app
    tag: "latest"
    pullPolicy: IfNotPresent
  
  port: 5000
  
  # Resource limits and requests
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  # Health probes
  livenessProbe:
    httpGet:
      path: /health
      port: 5000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readinessProbe:
    httpGet:
      path: /health
      port: 5000
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

  # Environment variables
  env:
    - name: MONGODB_URI
      value: "mongodb://mongodb:27017"
    - name: FLASK_ENV
      value: "production"

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 5000

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: geodish.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Namespace
namespace: geodish-app
