# Application configuration
app:
  name: geodish-app
  image:
    repository: 893692751288.dkr.ecr.ap-south-1.amazonaws.com/geodish-app
    tag: "23"
    pullPolicy: IfNotPresent
  
  port: 5000
  
  # Resource limits and requests
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  # Environment variables
  env:
    - name: MONGODB_URI
      value: "mongodb://mongodb:27017"
    - name: FLASK_ENV
      value: "production"

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 5000

# Namespace
namespace: geodish-app