# Logging stack configuration
namespace: logging

# Elasticsearch configuration
elasticsearch:
  replicas: 1
  minimumMasterNodes: 1
  
  # Persistent storage with Retain policy
  persistence:
    enabled: true
    labels:
      enabled: true
  
  volumeClaimTemplate:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "ebs-grafana-retain"
    resources:
      requests:
        storage: 20Gi
  
  # Resource limits
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  
  esJavaOpts: "-Xmx1g -Xms1g"
  
  # Single node cluster
  clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

# Kibana configuration
kibana:
  replicas: 1
  
  service:
    type: LoadBalancer
    port: 5601
  
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  
  elasticsearchHosts: "http://elasticsearch-master:9200"
  
  kibanaConfig:
    kibana.yml: |
      server.name: kibana
      server.host: "0.0.0.0"
      elasticsearch.hosts: [ "http://elasticsearch-master:9200" ]

# Fluent Bit configuration (lighter and more stable than Fluentd)
fluent-bit:
  kind: DaemonSet
  
  # Run on all nodes
  tolerations:
    - effect: NoSchedule
      operator: Exists
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Output to Elasticsearch
  config:
    outputs: |
      [OUTPUT]
          Name es
          Match *
          Host elasticsearch-master
          Port 9200
          Logstash_Format On
          Logstash_Prefix fluentbit
          Retry_Limit False
          Suppress_Type_Name On
    
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Kube_URL https://kubernetes.default.svc:443
          Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On