mongodb:
  image:
    repository: mongo
    tag: "6.0"
    pullPolicy: IfNotPresent
  
  port: 27017
  
  # Resource limits
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  
  # Persistence
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "gp2"

# Service
service:
  type: ClusterIP
  port: 27017

# Namespace
namespace: geodish-app