apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geodish-app.fullname" . }}-config
  labels:
    {{- include "geodish-app.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
data:
  # Application Configuration
  APP_ENV: {{ .Values.app.environment | quote }}
  APP_PORT: {{ .Values.app.port | quote }}
  FLASK_APP: "app.py"
  FLASK_ENV: {{ .Values.app.environment | quote }}
  FLASK_DEBUG: {{ .Values.app.flask.debug | quote }}
  LOG_LEVEL: "INFO"
  
  # Database Configuration
  {{- if .Values.mongodb.enabled }}
  MONGODB_HOST: {{ .Values.mongodb.host | quote }}
  MONGODB_PORT: {{ .Values.mongodb.port | quote }}
  MONGODB_DATABASE: {{ .Values.mongodb.database | quote }}
  MONGODB_URI: "mongodb://{{ .Values.mongodb.host }}:{{ .Values.mongodb.port }}/{{ .Values.mongodb.database }}"
  {{- end }}
  
  # Additional ConfigMap data from values
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

---
{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geodish-app.fullname" . }}-secrets
  labels:
    {{- include "geodish-app.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  # Flask Secret Key (base64 encoded)
  FLASK_SECRET_KEY: {{ .Values.app.flask.secretKey | b64enc | quote }}
  
  # Database Secrets (if authentication is enabled)
  {{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled }}
  MONGODB_USERNAME: {{ .Values.mongodb.auth.username | b64enc | quote }}
  MONGODB_PASSWORD: {{ .Values.mongodb.auth.password | b64enc | quote }}
  {{- end }}
  
  # Additional secrets from values
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
