apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geodish-app.fullname" . }}
  labels:
    {{- include "geodish-app.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace | quote }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "geodish-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Force pod restart on configmap/secret changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "geodish-app.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "geodish-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            # Environment variables from ConfigMap
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "geodish-app.fullname" . }}-config
                  key: APP_ENV
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "geodish-app.fullname" . }}-config
                  key: APP_PORT
            - name: FLASK_APP
              valueFrom:
                configMapKeyRef:
                  name: {{ include "geodish-app.fullname" . }}-config
                  key: FLASK_APP
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "geodish-app.fullname" . }}-config
                  key: FLASK_ENV
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "geodish-app.fullname" . }}-config
                  key: LOG_LEVEL
            {{- if .Values.mongodb.enabled }}
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "geodish-app.fullname" . }}-config
                  key: MONGODB_HOST
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "geodish-app.fullname" . }}-config
                  key: MONGODB_PORT
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "geodish-app.fullname" . }}-config
                  key: MONGODB_DATABASE
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ include "geodish-app.fullname" . }}-config
                  key: MONGODB_URI
            {{- end }}
            {{- if .Values.secrets.enabled }}
            # Environment variables from Secrets
            - name: FLASK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "geodish-app.fullname" . }}-secrets
                  key: FLASK_SECRET_KEY
            {{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled }}
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "geodish-app.fullname" . }}-secrets
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "geodish-app.fullname" . }}-secrets
                  key: MONGODB_PASSWORD
            {{- end }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
