# MongoDB Community Operator values

community-operator:
  operator:
    name: mongodb-kubernetes-operator
    namespace: devops-app

# MongoDB instance configuration
mongodb:
  name: geodish-mongodb
  # TOP LEVEL FIELD - not nested under spec
  scramCredentialsSecretName: geodish-mongodb-scram
  spec:
    members: 1
    type: ReplicaSet
    version: "6.0.5"
    
    security:
      authentication:
        modes: ["SCRAM"]
    
    users:
      - name: geodish-user
        db: admin
        passwordSecretRef:
          name: mongodb-secret
        roles:
          - name: clusterAdmin
            db: admin
          - name: userAdminAnyDatabase
            db: admin
          - name: readWriteAnyDatabase
            db: admin
    
    additionalMongodConfig:
      storage.wiredTiger.engineConfig.journalCompressor: zlib
    
    # ADDED: Persistent storage configuration using your EBS CSI driver
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: mongod
                resources:
                  limits:
                    cpu: 500m
                    memory: 512Mi
                  requests:
                    cpu: 250m
                    memory: 256Mi
        # ADDED: Persistent volume claim template for data persistence
        volumeClaimTemplates:
          - metadata:
              name: data-volume
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: "ebs-mongodb"  # Using your EBS CSI storage class
              resources:
                requests:
                  storage: 20Gi

# # Database credentials
# credentials:
#   username: geodish-user
#   password: GeoDishPass123!
#   database: geodish