apiVersion: v2
name: app-of-apps
description: App of Apps pattern for GeoDish deployment
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - argocd
  - gitops
  - app-of-apps

maintainers:
  - name: DevOps Student
    email: student@bootcamp.com

annotations:
  category: GitOps