# ArgoCD configuration
argocd:
  namespace: argocd

# Git repository configuration  
repo:
  url: https://github.com/kfiros94/geodish-gitops.git
  targetRevision: HEAD

# Application configurations
applications:
  mongodb:
    name: geodish-mongodb
    namespace: devops-app
    project: default
    path: helm-charts/mongodb
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
      retry:
        limit: 5
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 3m

  app:
    name: geodish-app
    namespace: devops-app
    project: default
    path: helm-charts/geodish-app
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
      retry:
        limit: 5
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 3m

  monitoring:
    name: geodish-monitoring
    namespace: monitoring
    project: default
    path: helm-charts/monitoring
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true           # ← FIX: Handle large CRDs
        - RespectIgnoreDifferences=true  # ← FIX: Ignore metadata differences
        - PrunePropagationPolicy=foreground
        - PruneLast=true
      retry:
        limit: 5
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 3m
  logging:
    name: geodish-logging
    namespace: logging
    project: default
    path: helm-charts/logging
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
      retry:
        limit: 5
        backoff:
          duration: 5s
          factor: 2
          maxDuration: 3m