apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ index .Values.applications "mongodb" "name" }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ index .Values.applications "mongodb" "syncWave" }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project.name }}
  source:
    repoURL: https://mongodb.github.io/helm-charts
    targetRevision: 0.9.0
    chart: community-operator
    helm:
      values: |
        # MongoDB Community Operator
        operator:
          image:
            repository: mongodb/mongodb-kubernetes-operator
            tag: 0.9.0
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
        
        # Create MongoDB Instance
        mongodb:
          enabled: true
          name: mongodb-geodish
          version: "6.0.5"
          members: 1
          type: ReplicaSet
          
          security:
            authentication:
              modes: ["SCRAM"]
            tls:
              enabled: false
              
          resources:
            limits:
              cpu: "500m"
              memory: "512M"
            requests:
              cpu: "250m" 
              memory: "256M"
              
          storage:
            size: 8Gi
            storageClass: "gp2"

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ index .Values.applications "mongodb" "namespace" }}
  syncPolicy:
    automated:
      {{- toYaml .Values.global.syncPolicy.automated | nindent 6 }}
    syncOptions:
      {{- toYaml .Values.global.syncPolicy.syncOptions | nindent 6 }}
    retry:
      {{- toYaml .Values.global.syncPolicy.retry | nindent 6 }}
