apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ index .Values.applications "mongodb" "name" }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ index .Values.applications "mongodb" "syncWave" }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project.name }}
  source:
    repoURL: https://github.com/kfiros94/geodish-gitops.git
    path: charts/mongodb-complete
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ index .Values.applications "mongodb" "namespace" }}
  syncPolicy:
    automated:
      {{- toYaml .Values.global.syncPolicy.automated | nindent 6 }}
    syncOptions:
      {{- toYaml .Values.global.syncPolicy.syncOptions | nindent 6 }}
    retry:
      {{- toYaml .Values.global.syncPolicy.retry | nindent 6 }}
