apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- toYaml .Values.mongodb.spec | nindent 2 }}
{{- if .Values.mongodb.scramCredentialsSecretName }}
scramCredentialsSecretName: {{ .Values.mongodb.scramCredentialsSecretName }}
{{- end }}