apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.credentials.password | b64enc }}
  connectionString: {{ printf "mongodb://%s:%s@%s-svc.%s.svc.cluster.local:27017/%s?authSource=admin" .Values.credentials.username .Values.credentials.password .Values.mongodb.name .Release.Namespace .Values.credentials.database | b64enc }}