apiVersion: v2
name: monitoring
description: Prometheus and Grafana monitoring stack
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: 55.5.0
    repository: https://prometheus-community.github.io/helm-charts

keywords:
  - monitoring
  - prometheus
  - grafana

maintainers:
  - name: DevOps Student
    email: student@bootcamp.com