---
# Simple MongoDB StatefulSet (no operator needed)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: geodish-app
  labels:
    app: mongodb
    app.kubernetes.io/component: database
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        app.kubernetes.io/component: database
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0.5
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "geodish"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "geodish123"
        - name: MONGO_INITDB_DATABASE
          value: "geodish"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 8Gi
      storageClassName: gp2
---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: geodish-app
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
